<?php

echo    '<div id="tracks-point-info-page" class="tracks-container hidden">
            <div class="toolbar">
                <a id="tracks-point-info-edit" class="two-button-toolbar-button-container" title="Edit point">
                    <img class="toolbar-button-icon" src="images/icons/edit.png" alt="Edit point">
                </a>
                <div id="tracks-point-info-remove" class="two-button-toolbar-button-container" title="Remove point">
                    <img class="toolbar-button-icon" src="images/icons/remove.png" alt="Remove point">
                </div>
            </div>
            <div class="tracks-container-inner-content">
                <div id="tracks-point-info-name" class="main-block big-text fixed-height-container-small overflow-auto width-three-fourths inline-block">                   
                </div>               
                <!--<div id="tracks-point-info-map" class="button-w-icon" title="Show on map">
                    <img src="images/icons/map.png" alt="Show on map">
                </div>-->
                <div id="tracks-point-info-coords" class="main-block">                 
                </div>
                <div id="tracks-point-info-image" class="main-block">
                    <img class="info-image" alt="No image">
                </div>
                <div id="tracks-point-info-description" class="main-block">
                </div>
                <div id="tracks-point-info-url" class="main-block">
                    <a target="_blank"></a>                 
                </div>
                <div id="tracks-point-info-audio" class="main-block">
                    <audio controls>
                    </audio>                 
                </div>
            </div>            
        </div>';

?>