<?php

echo '<div id="tracks-info-page" class="tracks-container hidden">
            <div class="toolbar">
                <a id="tracks-info-add" class="three-button-toolbar-button-container" title="Add point">
                    <img class="toolbar-button-icon" src="images/icons/add.png" alt="Add point">
                </a>
                <div id="tracks-info-edit" class="three-button-toolbar-button-container" title="Edit track">
                    <img class="toolbar-button-icon" src="images/icons/edit.png" alt="Edit track">
                </div>
                <div id="tracks-info-remove" class="three-button-toolbar-button-container" title="Remove track">
                    <img class="toolbar-button-icon" src="images/icons/remove.png" alt="Remove track">
                </div>
            </div>
            <div class="tracks-container-inner-content">
                <div id="tracks-info-name" class="main-block big-text fixed-height-container-small overflow-auto width-three-fourths inline-block">                   
                </div>
                <div id="tracks-info-map" class="button-w-icon">
                    <img src="images/icons/map.png" alt="Show on map">
                </div>
                <div id="tracks-info-category" class="main-block">                    
                </div>
                <div id="tracks-info-lang" class="main-block">                    
                </div>
                <div id="tracks-info-description" class="main-block">                    
                </div>
                <div class="main-block">
                    <ul id="tracks-points-list" class="main-list">
                    </ul>
                </div>
            </div>           
        </div>';

?>