<?php

define('GEO2TAG_USER', 'gets_user');
define('GEO2TAG_PASSWORD', 'gets_user_password');
define('GEO2TAG_EMAIL', 'gets_user@example.com');
define('ALL_USERS_TRUSTED', false);


define('DEFAULT_CATEGORY_ID', 1);

define('GEO2TAG_DB_STRING', "host=localhost dbname=geo2tag user=postgres");

define('GEO2TAG_SERVER_URL', "UNUSED");
define('GETS_SERVER_URL', 'http://localhost:8000');
define('GETS_SCRIPTS_URL', 'UNUSED');
define('AUTH_REDIRECT_URL', 'UNUSED');
define('UPLOAD_URL', 'UNUSED');
define('GOOGLE_APP_NAME', 'UNUSED');
define('GOOGLE_CLIENT_ID', 'UNUSED');
define('GOOGLE_SECRET_ID', 'UNUSED');

define('TESTING_MODE', true);

