<?php
define('GEO2TAG_SERVER_URL', 'geo2tag.cs.prv');
define('GETS_SERVER_URL', 'oss.fruct.org/projects/gets/service');
define('GETS_SCRIPTS_URL', 'geo2tag.cs.prv/gets/geo2tag.php');
define('UPLOAD_URL', 'http://oss.fruct.org/projects/gets/service/files/postFile.php');

define('GEO2TAG_USER', 'gets2');
define('GEO2TAG_PASSWORD', 'getsPWD');
define('GEO2TAG_EMAIL', 'manager@cs.karelia.ru');
define('GEO2TAG_DB_STRING', 'host=localhost dbname=geo2tag user=geo2tag');

define('GOOGLE_APP_NAME', 'GeTS-Service');
define('GOOGLE_CLIENT_ID', '710658254828-tntn2h772v22ilii1qgsvlfgrijrbg6e.apps.googleusercontent.com');
define('GOOGLE_SECRET_ID', 'y8fwnTyiEs-gsrCTLtfFyjXn');
?>
