<?php
define('GEO2TAG_SERVER_URL', 'geo2tag.cs.prv');
define('GETS_SERVER_URL', 'gets.cs.petrsu.ru/obstacle/service');
define('GETS_SCRIPTS_URL', 'gets.cs.petrsu.ru/obstacle/scripts/geo2tag.php');
define('UPLOAD_URL', 'http://' . GETS_SERVER_URL . '/files/postFile.php');

define('GEO2TAG_USER', 'obstacle-test');
define('GEO2TAG_PASSWORD', 'obstacle-test');
define('GEO2TAG_EMAIL', 'getsobstacletest@gmail.com');
define('GEO2TAG_DB_STRING', 'host=geo2tag.cs.prv dbname=geo2tag user=geo2tag password=geo2tag');

define('ALL_USERS_TRUSTED', true);

define('GOOGLE_APP_NAME', 'gets-obstacle');
define('GOOGLE_CLIENT_ID', '791672128240-dpo0ivbqq8o606vourt5feah1652215t.apps.googleusercontent.com');
define('GOOGLE_SECRET_ID', '7v_w8UuKevk4oGIguqwu1bHw');
?>
